sudo: required
services:
  - docker

before_install:
  - docker build -t arvin/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true arvin/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "ap-northeast-1"
  app:  "Arvin"
  env:  "Arvin-env"
  bucket_name:  "elasticbeanstalk-ap-northeast-1-721660830567"
  bucket_path:  "Arvin"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"
